### ISSUE TITLE
JavaScript error on result handling / JSON parsing

### ISSUE THREAD

**Issue by theorak** [comsolit/comsolit_suggest#1]
Following JavaScript error is reported when searching via searchbox:
SyntaxError: JSON.parse: unexpected character at line 5 column 1 of the JSON data

Input field layout:
`<input dir="auto" spellcheck="false" autocomplete="off" class="form-control typeahead tt-input" name="tx_indexedsearch[sword]" value="" placeholder="Suche" type="search">`

Environment:
dev context - Windows 8.1 - local xampp server (PHP 5.6.3)

My test result data read from JS: (sorry, would not let me attach a file)
=> onSuccess(JSON.parse(removeHTML(data)));
data:
`<html>
<head>
    <meta name="author" content="Kai Oswald Seidler">
    <meta http-equiv="cache-control" content="no-cache">
    <title>XAMPP 5.6.3</title>
    <frameset rows="74,*" marginwidth="0" marginheight="0" frameborder="0" border="0" borderwidth="0">    
        <frame name="head" src="head.php" scrolling=no>
        <frameset cols="150,*" marginwidth="0" marginheight="0" frameborder="0" border="0" borderwidth="0">    
            <frame name="navi" src="navi.php" scrolling=no>
            <frame name="content" src="start.php" marginwidth=20>
        </frameset>
    </frameset>
</head>
<body bgcolor=#ffffff>
</body>
</html>`
data: (removeHTML)
`"XAMPP 5.6.3            "`

I see two things: 
1) the <title> attribute content remains before parsing JSON
2) no results, there should be some, because
/?type=999&no_cache=1&tx_comsolitsuggest_suggest[search]=erdgas&tx_comsolitsuggest_suggest[method]=suggest
- actually returns JSON content

**Comment by ghost** [comment]
Hi theorak

Sorry, we have not tested the extension on Windows ;-)

The Extension we have running now in 3 TYPO3 Project all on a LAMP Stack.

Are you sure you have include the extension TypoScript on your global TS Template?

G Lars
