### ISSUE TITLE
v1.0.5 from TER: stuffes input field with elements but: Does nothing at all

### ISSUE THREAD

**Issue by p-Enzi** [comsolit/comsolit_suggest#2]
Using typo3 v7.2.6 with php 5.6 and comsolit_suggest 1.0.5 from TER.
The input field has the class="typeahead tx-indexedsearch-searchbox-sword sword"
Lots of code is added to this and some other fields in the html-code of the search-page.
The index-search itsself is working pretty well.
Im including for other jqueries on the page jQuery 2.1.4 from Google.
So this is the same version you are using, right?
I can see the js-code of your extension in the html, included after all other js-code of the page in the
/_TS_inlineFooter_/ section.
But suggestions are not given.
Do you have any ideas?

**Comment by ghost** [comment]
From your explanation it is not clear if it is a frontend Problem (conflict with JS) or if the extension ist not proper installed.
We need more Infos to help you.
