### ISSUE TITLE
Please add hint to documentation to use static templates

### ISSUE THREAD

**Issue by p-Enzi** [comsolit/comsolit_suggest#3]
Your documentation does not include the hint to use the static template of 
comsolit_suggest - but only with this constant/setup settings 
any extension code will be available in the indedex_search button with the class="typeahead"
setup.

**Comment by ghost** [comment]
Oh, I'm sorry this is not in the Docu. 
But it is logical for most TYPO3 Users.
We will add this to the docu!

**Comment by ghost** [comment]
Hint added in Docu - Version 1.0.6
