### ISSUE TITLE
How to set up an own suggest Query

### ISSUE THREAD

**Issue by HorstBaumann** [comsolit/comsolit_suggest#4]
great Extension - the only autocompleter which still works with Typo3 7.\* - thanks !
But how can I set up an individual suggest Query ? - when I create a new data-item (type: Query),
there are no input fields to edit ...?

**Comment by ghost** [comment]
Ok, we will hide this.
This should not be allowed to add a new query, the query is not changeable.

**Comment by ghost** [comment]
fix in version 1.1.1
