### ISSUE TITLE
TYPO3 10 Support

### ISSUE THREAD

**Issue by akoenig-clickstorm** [comsolit/comsolit_suggest#9]
Hello,
I am using this Extension on TYPO3 10 and it works quite well till now. So could you please add constraints for TYPO3 10 in ext_emconf and composer.php, so I dont have to use a local git repository to install this extension via composer?

Thanks

**Comment by ghost** [comment]
The compatibility of version 3.0.2 ist still set to 10.4 in emconf and composer

**Comment by akoenig-clickstorm** [comment]
There is no version 3.0.2 public available :(
https://packagist.org/packages/comsolit/comsolit_suggest

**Comment by ghost** [comment]
https://extensions.typo3.org/extension/easy_googlemap

**Comment by akoenig-clickstorm** [comment]
Wrong Extension: I am talking about comsolit/comsolit_suggest

**Comment by ghost** [comment]
Oh I'm so sorry!
comsolit_suggest latest Version is 3.0.0 and not supported for TYPO3 10.
If you want compatibility for 10 pull requests are welcome.
